HW11 Telnet Client
nimoism/gotus_hw pull request #11
Opened 2021-01-10 19:57 UTC by nimoism

## Домашнее задание №11 «Клиент TELNET»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2021-01-12 06:19 UTC, balabanovds requested changes
Хорошая работа!
Понравилось как тестируете с пайпами.

Есть замечания, которые стоит рассмотреть перед закрытием ПР
Если будут вопросы - обращайтесь (можно в Slack)

Успехов!

https://otus.ru/teacher-lk/homework/134171/8092/

2021-01-12 06:19 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		cancel()
это не имеет смысла, Вы слушаете контекст только в данном селекте

2021-01-12 06:19 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		logErr(f())
вызывая log.Fatal Вы жестко закрываете программу через os.Exit. А если там есть горутины которым надо мягко завершиться - дописать, закрыть коннект?
делать это в дочерних горутинах не стоит, лучше пробрасывать ошибку наверх и там обрабатывать

2021-01-12 15:52 UTC, nimoism commented on hw11_telnet_client/main.go
> +		cancel()
Да, убрал

2021-01-12 15:53 UTC, nimoism commented on hw11_telnet_client/main.go
> +		logErr(f())
Теперь main() просто логирует ошибки

2021-01-12 15:53 UTC, nimoism commented
@balabanovds 
Спасибо за замечания! Обновил код

2021-01-12 19:51 UTC, balabanovds commented
@nimoism добавьте меня в список коллабораторов

2021-01-12 20:17 UTC, balabanovds approved these changes, later dismissed
Спасибо за работу.

Пока оцениваю ее на 7/10

предлагаю Вам подумать как можно улучшить код.
если будут вопросы то я доступен в Slack или тут

Успехов!

2021-01-12 20:17 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	defer func() {
Интересное решение. :)
Но вот если представить, что функция большая - то я должен помнить, что где-то там был defer который логирует ошибку, да и err не должна переопределяться, иначе ничего не логируется (а у Вас в строке 29 как раз именно переопределение переменной)

можно подумать как упростить код и сделать его чуточку красивее - убрать этот defer, а также избавиться от контекста
подсказка: использовать небуферизированный канал

2021-01-12 20:17 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	if err := tc.Connect(); err != nil {
здесь у Вас переопределение err

2021-01-12 20:17 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	defer close(sigCh)
закрывать канал стоит когда кто-то его слушает и Вы хотите ему сообщить ему об этом
канал и так закроется когда закончится область видимости

2021-01-14 19:26 UTC, nimoism commented on hw11_telnet_client/main.go
> +	if err := tc.Connect(); err != nil {
Да, спасибо, опечатка

2021-01-14 19:27 UTC, nimoism commented on hw11_telnet_client/main.go
> +	defer close(sigCh)
Убрал явное закрытие канала

2021-01-14 19:29 UTC, nimoism commented on hw11_telnet_client/main.go
> +	defer func() {
Переделал обработку ошибок, теперь стало "площе"
Насчет избавиться от контекста - избавился, правда не понял, почему это упрощает код и делает красивее, ведь через канал наоборот больше обрабатыать и код длиннее получается, а выгод от этого я не вижу

2021-01-15 16:56 UTC, balabanovds commented on hw11_telnet_client/main.go
> +	defer func() {
а вот если сделать не канал страктов, а канал ошибок?

2021-01-17 14:57 UTC, nimoism commented on hw11_telnet_client/main.go
> +	defer func() {
Да, спасибо,так выглядит лучше

2021-01-18 05:13 UTC, balabanovds approved these changes
Есть небольшое замечание, но в целом 10/10

2021-01-18 05:13 UTC, balabanovds commented on hw11_telnet_client/main.go
> +		if err != nil {
У Вас горутины с `tc.Send`, `tc.Receive` повиснут на 34 строке, а основная горутина на селекте.
Когда кто-то отработает и запишет в канал, селект также завершится.
Поэтому проверять на `nil` тут лишнее.

2021-01-18 10:25 UTC, nimoism commented on hw11_telnet_client/main.go
> +		if err != nil {
Функции telnetClient.Send() и telnetClientюReceive() могут вернуть nil (в случае ^D или завершения сессии со стороны сервера), здесь выводятся "непредвиденные" ошибки

2021-01-19 12:35 UTC, merged