HW06 implement ExecutePipeline, add tests
nimoism/gotus_hw pull request #6
Opened 2020-10-24 07:15 UTC by nimoism

## Домашнее задание №6 «Пайплайн»

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2020-10-28 17:12 UTC, kulti requested changes
Крутые тесты и рассмотрен интересный случай, когда done не передали 👍 

Есть небольшая ошибочка в логике. Предлагаю ее поправить.

2020-10-28 17:12 UTC, kulti commented on hw06_pipeline_execution/pipeline.go
> +			out = terminator(out, done)
Получается, что в самый первый stage попадет входной канал, необернутый terminator'ом. Если in не закроют и вызовут done, то первый стейдж никогда не остановится.

2020-10-29 16:37 UTC, nimoism commented on hw06_pipeline_execution/pipeline.go
> +			out = terminator(out, done)
И правда, спасибо, поправил

2020-10-29 16:38 UTC, nimoism commented
> Крутые тесты и рассмотрен интересный случай, когда done не передали 
> 
> Есть небольшая ошибочка в логике. Предлагаю ее поправить.

@kulti 
Спасибо за замечания! Поправил что было

2020-10-29 17:20 UTC, kulti approved these changes
Теперь все верно. ДЗ принято - 10/10

2020-10-29 18:36 UTC, merged